import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import Navbar from './_components/Navbar';

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <header>
          <Navbar />
        </header>
        <main className="pt-14">{children}</main>
      </body>
    </html>
  );
}
